### ISSUE TITLE
ssf not working in background

### ISSUE THREAD

**Issue by wellsgz** [securesocketfunneling/ssf#17]
Hi, I managed to build ssf on CentOS 7, and it's running well at foreground.

However, the process seems stoping responding once it's run in background, e.g.

./ssfs -p 443 -c /etc/ssf/ssf.conf &

The port itself is listening but from log of a client trying to connect I could see nothing.

Appreciate if you could let me know how to gave it run in background as daemon?

**Comment by securesocketfunneling** [comment]
Hello,

Sorry for this very very late answer...

We are pleased to know that you managed to build our project on CentOS. Was it straightforward ?

Concerning the background running issue, we are pretty sure this is due to the user input needed for stopping the server (return key press). The process needs an input from stdin but since it is not foreground, the OS stops it. 
Hopefully, this stopping behavior has totally changed in the 2.1.0 version. This is now based on signals. (cf. branch develop).
I tested your command line with the new version and it worked. We also add verbose and quiet mode options to the CLI (`-v level`, `-q`).

We will provide new linux binaries (32 and 64bits) on the website ASAP.

Do not hesitate to give us feedback of your usage. This will clearly help us to improve this project.
