### ISSUE TITLE
Socket Reuse

### ISSUE THREAD

**Issue by ankitkk** [securesocketfunneling/ssf#35]
I am running into an issue where the server cannot bind to already bound udp ip:port 

on further inspection Looks  like the code is [commented](https://github.com/securesocketfunneling/ssf/blob/7587ab518d07285f689f3fe286dca7342711e83e/src/services/datagrams_to_fibers/datagrams_to_fibers.ipp#L58) out :(   

I believe the commented code should work. Not entirely sure why is it commented out.  Can we put it back ? :) 

Also, this is pretty great. Thanks for making this tool.

**Comment by securesocketfunneling** [comment]
Hi,

Indeed, this feature was up and running in a previous version.
It was commented because of a potential issue but we don't remember why...

We are working right now on the 2.3. We may reactivate this feature if there is no serious problem with it.
Your issue is now in our task list!

Thanks for your feedback! It is really appreciated :-)

**Comment by securesocketfunneling** [comment]
Hello @ankitkk,

We integrated your suggestions in the [version 3.0.0](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0).
You can check it out and send us feedback!
